### ISSUE TITLE
SIA requires the /zts/v1/instance endpoint is configured as unauthenticated ?

### ISSUE THREAD

**Issue by hiyosi** [yahoo/k8s-athenz-identity#17]
if I didn't configure the endpoint(`/zts/v1/instance`) served by ZTS as an no authentication, I would get an authentication error(401) from ZTS.
I think, the SIA doesn't set the client credentials while starting up, so we need to include `/zts/v1/instance` into `no_auth_uri` at `zts.properties`, does my understanding correct?

ref: https://github.com/yahoo/athenz/blob/master/core/zts/src/main/rdl/Instance.rdli#L41-L46

**Comment by prabushyam** [comment]
@hiyosi currently the OPA provider comes up on HTTP, and by default ZTS expects the provider to listen on TLS with Athenz issued certs. Since OPA doesn't support automatically watching and picking up refreshed TLS certs, we have disabled OPA TLS listener. The idea is to have a reverse proxy like Envoy to listen on Athenz issued certs for the provider and which makes a localhost HTTP to the OPA. But, we haven't had a chance to work on it yet.

**Comment by hiyosi** [comment]
> currently the OPA provider comes up on HTTP, and by default ZTS expects the provider to listen on TLS with Athenz issued certs.

Yes, I understand. 
On the other hand I asked above was it needs the endpoint requesting in the following places needs to be de-authenticated. 

https://github.com/yahoo/k8s-athenz-identity/blob/master/pkg/identity/identity.go#L116

I'm sorry for confusing questions.
